### ISSUE TITLE
HLL becomes incorrect if cardinality is over billions

### ISSUE THREAD

**Issue by liyang-gmt8** [addthis/stream-lib#107] opened 2016-04-29 23:16 UTC
```
@Override
public long cardinality() {
    double registerSum = 0;
    int count = registerSet.count;
    double zeros = 0.0;
    for (int j = 0; j < registerSet.count; j++) {
        int val = registerSet.get(j);
        registerSum += 1.0 / (1 << val);        // SHOULD BE -- 1L << val
        if (val == 0) {
            zeros++;
        }
    }
```

**Comment by szhem** [comment] 2017-03-20 22:02
@liyang-gmt8, I'm also interested in this issue, but unfortunately cannot reproduce it with the following example
```
public static void main(String[] args) {
    HyperLogLogPlus hllp = new HyperLogLogPlus(20, 25)

    long size = 10_000_000_000L
    for (long i = 0; i < size; i++) {
        hllp.offer(i)
    }

    System.out.printf("True Cardinality: %s%n", size)
    System.out.printf("Estimated Cardinality: %s%n", hllp.cardinality())
    System.out.printf("Estimated Error: %f%n", Math.abs((hllp.cardinality() - size) / (float) size))    
}
```
... and got the following results
```
True Cardinality: 10000000000
Estimated StreamLib Cardinality: 10010661180
Estimated StreamLib Error: 0.001066
```
Could you please help to find a sample input to reproduce this issue?

**Comment by abramsm** [comment] 2017-06-26 19:47
closing.  please re-open if you can provide a failing test case.

**Closed by abramsm** 2017-06-26 19:47 UTC
